-- Separate job functions; do not grant application roles directly to users here.
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS GOVAI_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS GOVAI_ANALYST;
CREATE ROLE IF NOT EXISTS GOVAI_GOVERNANCE_ADMIN;
CREATE ROLE IF NOT EXISTS GOVAI_RESTRICTED_ANALYST;
CREATE ROLE IF NOT EXISTS GOVAI_PIPELINE_ROLE;
CREATE ROLE IF NOT EXISTS GOVAI_DBT_ROLE;

-- Restricted analysts inherit ordinary analytics access, then receive explicit
-- raw access and masking-policy exceptions in later scripts.
GRANT ROLE GOVAI_ANALYST TO ROLE GOVAI_RESTRICTED_ANALYST;

-- SYSADMIN remains the parent for lifecycle management without using
-- ACCOUNTADMIN for daily work.
GRANT ROLE GOVAI_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE GOVAI_ANALYST TO ROLE SYSADMIN;
GRANT ROLE GOVAI_GOVERNANCE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE GOVAI_RESTRICTED_ANALYST TO ROLE SYSADMIN;
GRANT ROLE GOVAI_PIPELINE_ROLE TO ROLE SYSADMIN;
GRANT ROLE GOVAI_DBT_ROLE TO ROLE SYSADMIN;

USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_DATA_ENGINEER;
GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_ANALYST;
GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_RESTRICTED_ANALYST;
GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_PIPELINE_ROLE;
GRANT USAGE ON DATABASE GOVERNAI TO ROLE GOVAI_DBT_ROLE;

GRANT USAGE ON WAREHOUSE GOVAI_INGEST_WH TO ROLE GOVAI_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE GOVAI_INGEST_WH TO ROLE GOVAI_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE GOVAI_TRANSFORM_WH TO ROLE GOVAI_DBT_ROLE;
GRANT USAGE ON WAREHOUSE GOVAI_TRANSFORM_WH TO ROLE GOVAI_ANALYST;
GRANT USAGE ON WAREHOUSE GOVAI_TRANSFORM_WH TO ROLE GOVAI_RESTRICTED_ANALYST;
GRANT USAGE ON WAREHOUSE GOVAI_TRANSFORM_WH TO ROLE GOVAI_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_PIPELINE_ROLE;
-- Snowflake uses CREATE TABLE for temporary tables too. The loader needs this
-- only in RAW so COPY can validate in a session-scoped table before MERGE.
GRANT CREATE TABLE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DBT_ROLE;
GRANT USAGE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_RESTRICTED_ANALYST;
GRANT USAGE ON SCHEMA GOVERNAI.RAW TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_DATA_ENGINEER;

GRANT USAGE ON SCHEMA GOVERNAI.STAGING TO ROLE GOVAI_DBT_ROLE;
GRANT USAGE ON SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_DBT_ROLE;
GRANT USAGE ON SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA GOVERNAI.STAGING TO ROLE GOVAI_DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_DBT_ROLE;

GRANT USAGE ON SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_ANALYST;
GRANT USAGE ON SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNAI.CURATED TO ROLE GOVAI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNAI.ANALYTICS TO ROLE GOVAI_ANALYST;

GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_RESTRICTED_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_RESTRICTED_ANALYST;

GRANT CREATE MASKING POLICY ON SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE GOVAI_GOVERNANCE_ADMIN;
