USE ROLE SYSADMIN;
USE DATABASE GOVERNAI;

CREATE OR REPLACE FILE FORMAT GOVERNANCE.CSV_V1
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  EMPTY_FIELD_AS_NULL = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  COMMENT = 'Deterministic GovernAI CSV contract';

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
  CUSTOMER_ID STRING NOT NULL,
  FULL_NAME STRING NOT NULL,
  EMAIL STRING NOT NULL,
  PHONE STRING NOT NULL,
  STATE STRING NOT NULL,
  CUSTOMER_SINCE DATE NOT NULL,
  SEGMENT STRING NOT NULL,
  BATCH_ID STRING NOT NULL,
  SOURCE_SHA256 STRING NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_RAW_CUSTOMERS PRIMARY KEY (CUSTOMER_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS RAW.ACCOUNTS (
  ACCOUNT_ID STRING NOT NULL,
  CUSTOMER_ID STRING NOT NULL,
  OPENED_DATE DATE NOT NULL,
  ACCOUNT_STATUS STRING NOT NULL,
  CREDIT_LIMIT NUMBER(18,2) NOT NULL,
  BATCH_ID STRING NOT NULL,
  SOURCE_SHA256 STRING NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_RAW_ACCOUNTS PRIMARY KEY (ACCOUNT_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS RAW.TRANSACTIONS (
  TRANSACTION_ID STRING NOT NULL,
  ACCOUNT_ID STRING NOT NULL,
  TRANSACTION_TS TIMESTAMP_TZ NOT NULL,
  AMOUNT NUMBER(18,2) NOT NULL,
  MERCHANT_CATEGORY STRING NOT NULL,
  CHANNEL STRING NOT NULL,
  COUNTRY_CODE STRING NOT NULL,
  IS_FRAUD BOOLEAN NOT NULL,
  CONFIRMED_LOSS NUMBER(18,2) NOT NULL,
  BATCH_ID STRING NOT NULL,
  SOURCE_SHA256 STRING NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_RAW_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.BATCH_LOADS (
  BATCH_ID STRING NOT NULL,
  DATASET STRING NOT NULL,
  ASSET_ID STRING NOT NULL,
  SOURCE_KEY STRING NOT NULL,
  SOURCE_SHA256 STRING NOT NULL,
  EXPECTED_ROW_COUNT NUMBER NOT NULL,
  ROW_COUNT NUMBER NOT NULL DEFAULT 0,
  STATUS STRING NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  ERROR_MESSAGE STRING,
  CONSTRAINT PK_BATCH_LOADS PRIMARY KEY (BATCH_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.PIPELINE_EVENTS (
  EVENT_ID STRING NOT NULL,
  RUN_ID STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  EVENT_AT TIMESTAMP_TZ NOT NULL,
  ACTOR STRING NOT NULL,
  DETAILS VARIANT NOT NULL,
  CONSTRAINT PK_PIPELINE_EVENTS PRIMARY KEY (EVENT_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.RECONCILIATION_RESULTS (
  RECONCILIATION_ID STRING NOT NULL,
  RUN_ID STRING NOT NULL,
  BATCH_ID STRING NOT NULL,
  DATASET STRING NOT NULL,
  EXPECTED_ROWS NUMBER NOT NULL,
  ACTUAL_ROWS NUMBER,
  EXPECTED_SHA256 STRING NOT NULL,
  ACTUAL_SHA256 STRING,
  STATUS STRING NOT NULL,
  DETAILS STRING NOT NULL,
  RECONCILED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_RECONCILIATION PRIMARY KEY (RECONCILIATION_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.LINEAGE_EDGES (
  EDGE_ID STRING NOT NULL,
  UPSTREAM_ASSET_ID STRING NOT NULL,
  DOWNSTREAM_ASSET_ID STRING NOT NULL,
  TRANSFORMATION_TYPE STRING NOT NULL,
  TRANSFORMATION_DESCRIPTION STRING NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_LINEAGE_EDGES PRIMARY KEY (EDGE_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.ACCESS_POLICY_EVENTS (
  EVENT_ID STRING NOT NULL,
  POLICY_NAME STRING NOT NULL,
  OBJECT_NAME STRING NOT NULL,
  COLUMN_NAME STRING NOT NULL,
  ACTION STRING NOT NULL,
  ACTOR STRING NOT NULL,
  EVENT_AT TIMESTAMP_TZ NOT NULL,
  DETAILS VARIANT,
  CONSTRAINT PK_ACCESS_POLICY_EVENTS PRIMARY KEY (EVENT_ID) NOT ENFORCED
);

USE ROLE SECURITYADMIN;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT INSERT ON TABLE GOVERNAI.GOVERNANCE.ACCESS_POLICY_EVENTS TO ROLE GOVAI_GOVERNANCE_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.GOVERNANCE TO ROLE GOVAI_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNAI.RAW TO ROLE GOVAI_DATA_ENGINEER;
