-- Render with scripts/render_snowflake_sql.py. Never paste AWS keys here.
USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS GOVAI_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '__AWS_ROLE_ARN__'
  STORAGE_ALLOWED_LOCATIONS = ('s3://__S3_BUCKET__/validated/')
  COMMENT = 'Credential-free trust between Snowflake and GovernAI validated S3 zone';

-- Record STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID from this output,
-- then supply them to Terraform to complete the AWS role trust policy.
DESC INTEGRATION GOVAI_S3_INTEGRATION;

GRANT USAGE ON INTEGRATION GOVAI_S3_INTEGRATION TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE STAGE IF NOT EXISTS GOVERNAI.GOVERNANCE.S3_VALIDATED_STAGE
  URL = 's3://__S3_BUCKET__/'
  STORAGE_INTEGRATION = GOVAI_S3_INTEGRATION
  FILE_FORMAT = GOVERNAI.GOVERNANCE.CSV_V1
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Read-only governed stage rooted at the GovernAI data lake';

USE ROLE SECURITYADMIN;
GRANT USAGE ON INTEGRATION GOVAI_S3_INTEGRATION TO ROLE GOVAI_PIPELINE_ROLE;
GRANT USAGE ON STAGE GOVERNAI.GOVERNANCE.S3_VALIDATED_STAGE TO ROLE GOVAI_PIPELINE_ROLE;
