USE ROLE GOVAI_GOVERNANCE_ADMIN;
USE DATABASE GOVERNAI;
USE SCHEMA GOVERNANCE;

CREATE OR REPLACE MASKING POLICY NAME_MASK AS (VALUE STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('GOVAI_RESTRICTED_ANALYST') THEN VALUE
    ELSE '[MASKED]'
  END
  COMMENT = 'Full names visible only to restricted/PII analysts';

CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS (VALUE STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('GOVAI_RESTRICTED_ANALYST') THEN VALUE
    WHEN VALUE IS NULL THEN NULL
    ELSE LEFT(SPLIT_PART(VALUE, '@', 1), 1) || '***@' || SPLIT_PART(VALUE, '@', 2)
  END
  COMMENT = 'Restricted analysts see full email; other raw readers see partial mask';

CREATE OR REPLACE MASKING POLICY PHONE_MASK AS (VALUE STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('GOVAI_RESTRICTED_ANALYST') THEN VALUE
    WHEN VALUE IS NULL THEN NULL
    ELSE '***-***-' || RIGHT(VALUE, 4)
  END
  COMMENT = 'Restricted analysts see full phone; other raw readers see last four';

CREATE OR REPLACE MASKING POLICY FINANCIAL_AMOUNT_MASK AS (VALUE NUMBER(18,2)) RETURNS NUMBER(18,2) ->
  CASE
    WHEN IS_ROLE_IN_SESSION('GOVAI_RESTRICTED_ANALYST')
      OR IS_ROLE_IN_SESSION('GOVAI_DBT_ROLE')
      OR IS_ROLE_IN_SESSION('GOVAI_PIPELINE_ROLE') THEN VALUE
    ELSE NULL
  END
  COMMENT = 'Financial fields require restricted analytics or pipeline transformation role';

ALTER TABLE GOVERNAI.RAW.CUSTOMERS MODIFY COLUMN FULL_NAME
  SET MASKING POLICY GOVERNAI.GOVERNANCE.NAME_MASK;
ALTER TABLE GOVERNAI.RAW.CUSTOMERS MODIFY COLUMN EMAIL
  SET MASKING POLICY GOVERNAI.GOVERNANCE.EMAIL_MASK;
ALTER TABLE GOVERNAI.RAW.CUSTOMERS MODIFY COLUMN PHONE
  SET MASKING POLICY GOVERNAI.GOVERNANCE.PHONE_MASK;
ALTER TABLE GOVERNAI.RAW.ACCOUNTS MODIFY COLUMN CREDIT_LIMIT
  SET MASKING POLICY GOVERNAI.GOVERNANCE.FINANCIAL_AMOUNT_MASK;
ALTER TABLE GOVERNAI.RAW.TRANSACTIONS MODIFY COLUMN AMOUNT
  SET MASKING POLICY GOVERNAI.GOVERNANCE.FINANCIAL_AMOUNT_MASK;
ALTER TABLE GOVERNAI.RAW.TRANSACTIONS MODIFY COLUMN CONFIRMED_LOSS
  SET MASKING POLICY GOVERNAI.GOVERNANCE.FINANCIAL_AMOUNT_MASK;

INSERT INTO GOVERNAI.GOVERNANCE.ACCESS_POLICY_EVENTS
  (EVENT_ID,POLICY_NAME,OBJECT_NAME,COLUMN_NAME,ACTION,ACTOR,EVENT_AT,DETAILS)
SELECT UUID_STRING(),'NAME_MASK','GOVERNAI.RAW.CUSTOMERS','FULL_NAME','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}')
UNION ALL SELECT UUID_STRING(),'EMAIL_MASK','GOVERNAI.RAW.CUSTOMERS','EMAIL','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}')
UNION ALL SELECT UUID_STRING(),'PHONE_MASK','GOVERNAI.RAW.CUSTOMERS','PHONE','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}')
UNION ALL SELECT UUID_STRING(),'FINANCIAL_AMOUNT_MASK','GOVERNAI.RAW.ACCOUNTS','CREDIT_LIMIT','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}')
UNION ALL SELECT UUID_STRING(),'FINANCIAL_AMOUNT_MASK','GOVERNAI.RAW.TRANSACTIONS','AMOUNT','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}')
UNION ALL SELECT UUID_STRING(),'FINANCIAL_AMOUNT_MASK','GOVERNAI.RAW.TRANSACTIONS','CONFIRMED_LOSS','APPLIED',CURRENT_USER(),CURRENT_TIMESTAMP(),PARSE_JSON('{"phase":"2"}');
