-- Read-only evidence queries. Save outputs with the live verification report.
USE ROLE GOVAI_GOVERNANCE_ADMIN;
USE WAREHOUSE GOVAI_TRANSFORM_WH;

SELECT BATCH_ID, DATASET, SOURCE_SHA256, EXPECTED_ROW_COUNT, ROW_COUNT, STATUS
FROM GOVERNAI.GOVERNANCE.BATCH_LOADS
ORDER BY STARTED_AT;

SELECT RUN_ID, BATCH_ID, DATASET, EXPECTED_ROWS, ACTUAL_ROWS,
       EXPECTED_SHA256, ACTUAL_SHA256, STATUS
FROM GOVERNAI.GOVERNANCE.RECONCILIATION_RESULTS
ORDER BY RECONCILED_AT;

SELECT EDGE_ID, UPSTREAM_ASSET_ID, DOWNSTREAM_ASSET_ID, TRANSFORMATION_TYPE
FROM GOVERNAI.GOVERNANCE.LINEAGE_EDGES
ORDER BY EDGE_ID;

SHOW MASKING POLICIES IN SCHEMA GOVERNAI.GOVERNANCE;
SHOW GRANTS TO ROLE GOVAI_ANALYST;
SHOW GRANTS TO ROLE GOVAI_RESTRICTED_ANALYST;
SHOW GRANTS TO ROLE GOVAI_PIPELINE_ROLE;
SHOW GRANTS TO ROLE GOVAI_DBT_ROLE;
